const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const { createServer } = require('../tools/serve.cjs');
const fs = require('node:fs');
(async () => {
  const server = createServer();
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ headless: true });
  let checks = 0;
  const check = (name, condition) => { assert.ok(condition, name); console.log(`PASS ${name}`); checks++; };
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
    // Deterministic network failure, with the real hls.js lifecycle still running.
    await context.route('https://camerai1.iticfoundation.org/**', route => route.fulfill({ status: 503, body: 'Offline test', headers: { 'access-control-allow-origin': '*' } }));
    await context.route('https://fonts.googleapis.com/**', route => route.abort());
    const page = await context.newPage();
    await page.clock.install();
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(url); await page.locator('.tile').first().waitFor();
    check('default layout has 4 unique cameras', await page.locator('.tile').count() === 4);
    check('automatic tour is off by default', await page.locator('#auto').getAttribute('aria-pressed') === 'false');
    await page.fill('#search', 'ccs03');
    await page.waitForFunction(() => document.querySelectorAll('.tile').length === 1);
    check('search by camera ID', await page.locator('.tile').getAttribute('data-id') === '03');
    await page.locator('.favorite-button').click();
    check('favorite updates without losing the current camera', await page.locator('.favorite-button').getAttribute('aria-pressed') === 'true');
    await page.reload(); await page.locator('.tile').first().waitFor();
    check('favorites survive reload', await page.locator('#favorite-count').textContent() === '1');
    await page.click('#favorites');
    check('favorite filter shows the saved camera', await page.locator('.tile').count() === 1);
    await page.locator('.favorite-button').click();
    check('removing last favorite shows actionable empty state', await page.locator('#empty').isVisible() && (await page.locator('#empty-title').textContent()).includes('ยังไม่มี'));
    await page.click('#reset-filters');
    await page.fill('#search', 'no camera exists');
    await page.locator('#empty').waitFor({ state: 'visible' });
    check('empty search disables pagination', await page.locator('#next').isDisabled());
    await page.click('#clear-search');
    await page.fill('#search', 'วัดโสธร');
    await page.waitForTimeout(250);
    check('Thai search returns matching cameras', await page.locator('.tile').count() > 0);
    await page.fill('#search', ''); await page.waitForTimeout(250);
    await page.locator('#search').press('Space');
    check('typing space does not trigger automatic tour', await page.locator('#auto').getAttribute('aria-pressed') === 'false');
    await page.click('#clear-search');
    await page.selectOption('#group', '5');
    check('intersection filtering preserves shared cameras', await page.locator('.tile').count() === 4);
    await page.selectOption('#group', '-1');
    await page.click('[data-n="4"]');
    check('four camera layout', await page.locator('.tile').count() === 4);
    await page.locator('.camera-open').first().click();
    check('focus mode exposes an explicit return control', await page.locator('#exit-focus').isVisible());
    await page.waitForTimeout(150);
    check('focus mode releases hidden streams', await page.locator('.tile:not(.focused)[data-state="paused"]').count() === 3);
    await page.keyboard.press('Escape');
    check('Escape restores camera grid', !(await page.locator('#exit-focus').isVisible()));
    await page.click('#next');
    check('pagination changes visible cameras', await page.locator('.tile').first().getAttribute('data-id') === '00');
    await page.click('#help');
    check('help dialog is keyboard accessible', await page.locator('#help-dialog').evaluate(el => el.open));
    await page.keyboard.press('Escape');
    await context.setOffline(true);
    await page.locator('#network-notice').waitFor({ state: 'visible' });
    check('offline state releases all streams', await page.locator('.tile:not([data-state="paused"])').count() === 0);
    check('paused cameras announce their current accessible status', (await page.locator('.camera-open').first().getAttribute('aria-label')).includes('พักการเชื่อมต่อ'));
    await context.setOffline(false);
    await page.locator('#network-notice').waitFor({ state: 'hidden' });
    check('online state reconnects streams', await page.locator('.tile[data-state="paused"]').count() === 0);
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange')); });
    check('hidden document releases all streams', await page.locator('.tile:not([data-state="paused"])').count() === 0);
    await page.evaluate(() => { delete document.hidden; document.dispatchEvent(new Event('visibilitychange')); });
    check('visible document resumes streams', await page.locator('.tile[data-state="paused"]').count() === 0);
    // Test tour by advancing the browser clock, without a wall-clock sleep.
    await page.click('#auto');
    const before = await page.locator('#page').textContent();
    await page.clock.runFor(15500);
    check('tour advances after the selected interval', await page.locator('#page').textContent() !== before);
    await page.click('#auto'); await page.clock.resume();
    for (const width of [320, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      await page.waitForTimeout(200);
      check(`no horizontal overflow at ${width}px`, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(250);
    check('phone uses a swipe view', await page.locator('#grid').evaluate(el => el.classList.contains('swipe')));
    check('only one phone camera connects at once', await page.locator('.tile:not([data-state="paused"])').count() === 1);
    await page.locator('.tile:not([data-state="paused"]) video').evaluate(video => video.dispatchEvent(new Event('playing')));
    check('normal phone video does not expose an inactive expand button', await page.locator('.tile').first().locator('.camera-open').isHidden());
    await page.click('#next'); await page.waitForTimeout(150);
    check('phone navigation updates camera index', (await page.locator('#page').textContent()).includes('2 / 40'));
    check('swipe releases previous player', await page.locator('.tile:not([data-state="paused"])').count() === 1);
    await page.click('[data-n="all"]'); await page.waitForTimeout(150);
    check('phone all view shows 40 cameras without connecting all streams', await page.locator('.tile').count() === 40 && await page.locator('.tile:not([data-state="paused"])').count() < 12);
    await page.locator('.camera-open').nth(1).click(); await page.waitForTimeout(200);
    check('opening a phone grid camera selects the correct swipe camera', (await page.locator('#page').textContent()).includes('2 / 40'));
    await page.goto(url + '/#test');
    await page.reload();
    check('legacy self-check entry remains available', await page.title() === 'TEST PASS');
    check('no uncaught page errors', errors.length === 0);
    await page.setViewportSize({ width: 1440, height: 900 });
    // Corrupt storage, unavailable player and storage denial must keep navigation usable.
    await page.evaluate(() => localStorage.setItem('cctv', '{broken'));
    await context.route('**/vendor/hls-1.7.3.min.js', route => route.abort());
    await page.goto(url + '/?player=hls');
    check('missing player library does not break controls', await page.locator('.tile').count() === 4);
    await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new Error('Denied'); }; });
    await page.reload(); await page.locator('.favorite-button').first().click();
    check('storage denial still permits favorites for this visit', await page.locator('#favorite-count').textContent() === '1');
    check('no uncaught errors after fallback cases', errors.length === 0);
    fs.mkdirSync('docs/reviews/evidence', { recursive: true });
    fs.writeFileSync('docs/reviews/evidence/browser-results.json', JSON.stringify({ checks, errors, at: new Date().toISOString() }, null, 2) + '\n');
    console.log(`${checks} browser checks passed`);
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(error => { console.error(error); process.exitCode = 1; });
